/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class suskun_nn_QuantizedDnn */

#ifndef _Included_suskun_nn_QuantizedDnn
#define _Included_suskun_nn_QuantizedDnn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_suskun_nn_QuantizedDnn_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    deleteLazyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_suskun_nn_QuantizedDnn_deleteLazyContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_suskun_nn_QuantizedDnn_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    getContext
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_suskun_nn_QuantizedDnn_getContext
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    calculateUntilOutput
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_suskun_nn_QuantizedDnn_calculateUntilOutput
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    calculateLazy
 * Signature: (JI[B)[F
 */
JNIEXPORT jfloatArray JNICALL Java_suskun_nn_QuantizedDnn_calculateLazy
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    calculate
 * Signature: (J[FIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_suskun_nn_QuantizedDnn_calculate
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jint, jint);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    inputDimension
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_suskun_nn_QuantizedDnn_inputDimension
  (JNIEnv *, jobject, jlong);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    outputDimension
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_suskun_nn_QuantizedDnn_outputDimension
  (JNIEnv *, jobject, jlong);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    layerDimension
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_suskun_nn_QuantizedDnn_layerDimension
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     suskun_nn_QuantizedDnn
 * Method:    layerCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_suskun_nn_QuantizedDnn_layerCount
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif