/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class suskun_nn_FastNativeDnn */

#ifndef _Included_suskun_nn_FastNativeDnn
#define _Included_suskun_nn_FastNativeDnn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     suskun_nn_FastNativeDnn
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_suskun_nn_FastNativeDnn_initialize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
